== 11970 Message Controller Generation

=== 1 Abstract

When connecting an xtUML-generated application to a browser-based client it is often necessary to produce a message controller class that serves as an intermediary between the xtUML server application and the communication mechanism to the client(s). This class contains a method for each port activity of a marked interface. These methods handle serialization of messaging to the client and deserialization of messaging from the client to the xtUML application. 

This topic, <<dr-1>>, now subsumes <<dr-2>>. 

=== 2 Introduction and Background

Some web frameworks, such as Spring, require a message controller class to handle message traffic flowing between a server application and its clients.   Manually writing such classes is tedious and error-prone, so this feature automates the process.

Refer to the hand-coded message controller classes within Version 1.0.0 of the 
https://github.com/johnrwolfe/CarPark/tree/master/Deployment/src/main/java/deployment[CarPark Deployment project] 
for examples.

The CarPark example employs a _shell component_ to represent each type of client.  This idiom minimizes the number of generated files that must be manually modified and maintained when connecting a generated application to a client without modifying the model compiler.  However, the shell component adds no value and can be eliminated once the model compiler is capable of generating message controllers.

=== 3 Requirements

. A mark specifies for which ports a message controller class must be generated.
. WebSocket communication within the Spring framework is supported.

=== 4 Analysis

Currently, only WebSocket communication within the Spring framework is supported.  

Marking is applied on a port boundary, and the generated port class includes the message controller for the marked port.

=== 5 Design

The message controller must provide methods for handling messages outgoing from the application and inbound to the application.

The Spring framework requires that an inbound message handling method be prefixed with a '@MessageMapping (/xxx)" annotation where xxx names the message to be handled by the method. The handler method invokes the corresponding port activity in the application, extracting parameters from the received message instance. 

Messages originating from an application activity invoke an outbound handler method which creates an instance of the appropriate message and invokes Spring's "convertAndSend" adding a destination identifier. The destination identifier is of the form "/topic/xxx/yyy"; a client can subscribe to topic xxx, perhaps refined by yyy to identify a particular client instance.


=== 6 Work required

. Add a mark named `SpringWebSocket` to be applied to a port.
. Modify template for a generated port to include generation of a message controller.
. Develop template(s) for both inbound and outbound message handling in the message controller.
. Update render operations as necessary to support generation of message controller within a generated port class.

=== 7 Implementation Comments

This https://github.com/amullarney/ciera/tree/Ciera11970_msgCtrl[branch] is a prototype of message controller generation. +
It does not take the step of eliminating the shell component.

As noted in the issue, during implementation it became apparent that the controller functionality could be realized 
directly within the rendering of a marked port. The port must be annotated as `@Controller` which has repercussions 
for application initialization as port instantiation will now be accomplished by the Spring framework.

Spring-compliant message classes are generated for the inbound-to-xtUML messages. The Port provides methods to accept 
these instances, extract parameter values from them and invoke corresponding Port activities. Outbound messages are 
delivered to browser-based clients as instances of a generic Spring-compliant message carrying a JSON Object with a 
`messageName` key for identification and a `payload` key which returns a JSON array of key-value pairs from which 
parameter data is retrieved.

The Port class is augmented with an auxiliary Port Descriptor class which is subtyped to allow deferred operations to 
provide rendering modifications. The Application class is similarly subtyped to provide for different initialization.

A number of markings are provided to specify an Application as SpringApplication and to designate a Port as WebSocket-enabled 
and to refine certain of its characteristics. See https://github.com/MaileTechnical/ciera/wiki/Marking[the Maile Technical wiki
page on marking] for details.

Note: Port, Component, and Application make use of `Singleton` methods to retrieve instance values as needed. This 
constrains a Spring-enabled deployment to a single Application which does not contain multiple instances of any Component.


=== 8 Acceptance Test

Version 2.0.0 of both the https://github.com/MaileTechnical/PilotPayroll[Payroll] and https://github.com/MaileTechnical/CarPark[CarPark] 
applications have successfully been built and run.

=== 9 User Documentation

https://github.com/MaileTechnical/ciera/wiki/Marking

=== 10 Code Changes

https://github.com/amullarney/ciera/tree/Ciera11970_msgCtrl


=== 11 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/11970
. [[dr-2]] https://support.onefact.net/issues/11971


