== inst_ref<>, inst_ref_set<> Interface-message Parameters

=== 1 Abstract

At present, interface-message parameters of type `inst_ref<>` and `inst_ref_set<>` are 
not supported.  This work adds support for such parameters.  

=== 2 Introduction and Background

Refer to <<dr-1>>, <<dr-2>> and <<dr-3>>for background.

=== 3 Requirements

. Support interface-message parameters of type `inst_ref<>`.
. Support interface-message parameters of type `inst_ref_set<>`.
. Serialize as a JSON string each instance referenced by a parameter of type
`inst_ref<>` or `inst_ref_set<>`. 
. The values of all application attributes and current state are passed for each 
parameter of type `inst_ref<>`.
. The instance population in the sending component is not affected by sending 
one or more instances as message parameters.
. Each instance received as a message parameter is added to the instance population
of the receiving component.
. Establishing associations involving received instances is the responsibility
of the model in the receiving component as only that component has sufficient knowledge
to determine which associations to establish and when to do so.

=== 4 Analysis

The xtUML editor supports interface-message parameters of type `inst_ref<>` and 
`inst_ref_set<>` as does Verifier and MC-3020.  This support is useful both for communication 
between xtUML components sharing a common class model and for interaction between 
xtUML components and external code.  The alternative involves modeled data marshaling,
which is inconvenient and tedious to build and maintain.  

Serialization of interface-message parameters as JSON strings is currently supported
for core types, and leveraging this approach for `inst_ref<>` and `inst_ref_set<>`
parameters is sufficient for present needs. This requires generation of `serialize` and 
`deserialize` methods for the classes involved. Note that the `serialize` method must invoke 
attribute `get` methods to correctly evaluate derived attribute values.

While use of a class as the type of a Formal Parameter of a Port Message could 
be determined by a navigation at render time, the complexity of that navigation, 
taken together with the low probablity in general of such use, has driven a decision 
to set an attribute on the Class on discovery of such use during Message transform.

=== 5 Design

==== 5.1 Outgoing Messages

Each interface-message parameter of type `inst_ref<>` is converted 
to a JSON string representing the attributes of the referenced instance.  

Each interface-message parameter of type `inst_ref_set<>` is converted 
to a JSON string representing each referenced instance contained within the set.

==== 5.2 Incoming Messages

Upon receipt of an interface message containing a parameter of type `inst_ref<>`
the JSON string representing the instance is converted into an instance 
of the appropriate class, added to the relevant collections (e.g., instance population and
change log for the receiving component), and made accessible to the 
port-message activity via the `param` keyword.

Similarly, a parameter of type `inst_ref_set<>` is de-serialized from a JSON
string into a collection of instances of the appropriate class 
and made accessible to the port-message activity via the `param` keyword.

==== 5.3 Shared Class Interfaces

Two components sending instances as message parameters to one another must both
refer, via package reference, to a shared definition of the class in question.  The Java
class generated for each xtUML class in a component, whether shared or not, is specialized based on the 
component using it.

Java allows an interface definition to extend another such definition, so a
component-independent interface for each xtUML class is added by this work such
that every xtUML class is represented by:

* A component-independent interface which publishes nothing but its name.
* An extended component-specific interface which publishes:
** xtUML-model-level attribute accessors
** xtUML-model-level operations

Component-independent interface definitions are only realized as files when the class is used in the context 
of a message parameter; the emitted files are placed in the root package.

The location of component-dependent interface definitions is not changed by this work.

An xtUML interface definition may be referenced by many different ports
sprouted by many different components.  A single Java interface is generated 
for each xtUML interface definition.  For any message carrying a parameter 
of type `inst_ref<>`, the component-independent interface representing 
the class of interest must be used when declaring parameters accepted by methods
declared within such an interface.

For an xtUML port formalized by an interface, a Java class that implements the 
relevant Java interface is generated.  Methods associated with messages carrying 
parameters of type `inst_ref<>` must then use the component-independent 
interface representing the class of interest when declaring parameters of type
`inst_ref<>`. However, the port implementation receiving an `inst_ref<>`
must invoke the component-specific implementation of static deserialize in order 
to construct the appropriate instance. 

To summarize, for an interface message carrying a parameter of type `inst_ref<>`, the
component-independent interface representing the relevant class is used to declare
arguments for methods declared or defined within the:

* Java interface representing the xtUML interface of interest
* Java port classes representing xtUML ports formalized by the xtUML interface of interest

Any method representing a port-message activity accepting a parameter of type `inst_ref<>`, 
defined within a port class, requires special treatment to allow component-specific use of the 
incoming argument, which is declared using the component-independent interface representing the 
class in question. This is achieved by using a specialized name for the argument in the port-message 
activity declaration and introducing a type cast which allows component-specific use of the argument 
value within the body of the activity.

Work required for the resolution of issue 12191 <<dr-2>> has some overlap with the modifications required 
for this issue. Issue 12191 explicitly represents, in the architecture, the separation of the 
component-independent definition of a class from the component-specific class-in-component representation.

It further seems reasonable to serialize the entire message if any of the message parameters are of type 
`inst_ref<>` or `inst_ref_set<>`. Issue 12287 <<dr-3>> has provided the means to serialize messages based on an interface mark.
This work adds recognition of such a parameter as a trigger to serialize a message.

==== 5.4 File imports

Adding serialization methods to a class requires that appropriate exception handling be supported which entails 
modifying the selectivity of adding exception imports. For simplicity, all class implementations now import XtumlException.


==== 6.1 Model Compiler

. Create interface definition templates to generate component-independent interfaces for all classes, placed in the root package.
. Modify existing component-specific interface templates to extend the component-independent class interface.
. Add a `serialize()` method and a static `deserialize()` method to the component-specific implementations of each class. While 
APIs exist for such transformations, generating methods by iteration over class attributes allows for suppression of referential attributes. Also, JSON deserialization appears to need to create the target instance, but Ciera requires the constructor to be given a context.
. Modify template for generating Java interface representing xtUML interface definition to use component-independent interface for 
any class used as a message parameter.
. Modify template for generating port class to use component-independent interface for any class used as a message parameter.
. Modify template for generating port-message-activity method to cast each `inst_ref<>` or `inst_ref_set<>` parameter variable to the component-specific
interface variable used within the method body, initializing this variable with the value of the incoming parameter.

==== 6.2 Test Cases

Develop a model supporting the test cases enumerated in <<8>>.


=== 7 Implementation Comments

See reference below to "proof-of-concept" hand-edited example.

=== 8 Acceptance Test

The basis for all test cases listed below is a model containing the 
following elements:

* an interface definition with messages carrying parameters
of type `inst_ref<>` and `inst_ref_set<>` flowing from the provider
* two components connected by the interface described above

Each test case involves the provider sending a single interface message, 
the contents of which are specific to the test case.  The receiving component
verifies that the contents of the message are as expected.

.Test cases:
. one parameter of type `inst_ref<>` referring to an instance of a class
containing at least one attribute of each core type
. one parameter of type `inst_ref<>` containing an empty instance handle
. one parameter of type `inst_ref_set<>` containing at least three instance
handles for a class containing at least one attribute of each core type
. one parameter of type `inst_ref_set<>` containing a single instance handle
for a class containing at least one attribute of each core type
. one parameter of type `inst_ref_set<>` containing an empty instance-handle
set

=== 9 User Documentation

Since lack of support for interface-message parameters of type `inst_ref<>` and 
`inst_ref_set<>` is not mentioned in the user documentation, no documentation
changes are required.

=== 10 Code Changes


----
 Put the file list here
----

=== 11 Document References

. [[dr-1]] https://support.onefact.net/issues/12002[12002: Support interface message parameters of type inst_ref and inst_ref_set]
. [[dr-2]] https://support.onefact.net/issues/12191[12191: Reusing a class in multiple domains]
. [[dr-3]] https://support.onefact.net/issues/12287[12287: Replace positional Port Message parameters with key-value pair encoding]
